// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED  EventType = 0
	EventType_EVENT_TYPE_TOOL_THOUGHT EventType = 1
	EventType_EVENT_TYPE_TOOL_CALL    EventType = 2
	EventType_EVENT_TYPE_TOOL_RESULT  EventType = 3
	EventType_EVENT_TYPE_RESULT       EventType = 4
	// —— Plan-Execute 加性扩展（仍 v1，线兼容）——
	EventType_EVENT_TYPE_PLAN_THOUGHT EventType = 5 // 规划器思考（复用 ThoughtPayload，带 planner_round_id）
	EventType_EVENT_TYPE_PLAN         EventType = 6 // 计划快照（PlanPayload）
	EventType_EVENT_TYPE_TASK         EventType = 7 // 单个 <sep> 子任务（TaskPayload）
	// —— M11 HITL 加性扩展（仍 v1）——
	EventType_EVENT_TYPE_APPROVAL_REQUEST EventType = 8 // 人工审批请求（ApprovalPayload；finish 恒 false——审批=run 边界）
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_TOOL_THOUGHT",
		2: "EVENT_TYPE_TOOL_CALL",
		3: "EVENT_TYPE_TOOL_RESULT",
		4: "EVENT_TYPE_RESULT",
		5: "EVENT_TYPE_PLAN_THOUGHT",
		6: "EVENT_TYPE_PLAN",
		7: "EVENT_TYPE_TASK",
		8: "EVENT_TYPE_APPROVAL_REQUEST",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":      0,
		"EVENT_TYPE_TOOL_THOUGHT":     1,
		"EVENT_TYPE_TOOL_CALL":        2,
		"EVENT_TYPE_TOOL_RESULT":      3,
		"EVENT_TYPE_RESULT":           4,
		"EVENT_TYPE_PLAN_THOUGHT":     5,
		"EVENT_TYPE_PLAN":             6,
		"EVENT_TYPE_TASK":             7,
		"EVENT_TYPE_APPROVAL_REQUEST": 8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ToolCallStatus int32

const (
	ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED ToolCallStatus = 0
	ToolCallStatus_TOOL_CALL_STATUS_RUNNING     ToolCallStatus = 1
	ToolCallStatus_TOOL_CALL_STATUS_SUCCESS     ToolCallStatus = 2
	ToolCallStatus_TOOL_CALL_STATUS_FAILED      ToolCallStatus = 3
)

// Enum value maps for ToolCallStatus.
var (
	ToolCallStatus_name = map[int32]string{
		0: "TOOL_CALL_STATUS_UNSPECIFIED",
		1: "TOOL_CALL_STATUS_RUNNING",
		2: "TOOL_CALL_STATUS_SUCCESS",
		3: "TOOL_CALL_STATUS_FAILED",
	}
	ToolCallStatus_value = map[string]int32{
		"TOOL_CALL_STATUS_UNSPECIFIED": 0,
		"TOOL_CALL_STATUS_RUNNING":     1,
		"TOOL_CALL_STATUS_SUCCESS":     2,
		"TOOL_CALL_STATUS_FAILED":      3,
	}
)

func (x ToolCallStatus) Enum() *ToolCallStatus {
	p := new(ToolCallStatus)
	*p = x
	return p
}

func (x ToolCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (ToolCallStatus) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x ToolCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCallStatus.Descriptor instead.
func (ToolCallStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type IngestDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // 归属（服务端定 kb=owner:{owner_id}，客户端不可指定 kb）
	Attachment    *Attachment            `protobuf:"bytes,2,opt,name=attachment,proto3" json:"attachment,omitempty"`          // 已上传对象引用（Go 侧已校验 key 归属）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestDocumentRequest) Reset() {
	*x = IngestDocumentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestDocumentRequest) ProtoMessage() {}

func (x *IngestDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestDocumentRequest.ProtoReflect.Descriptor instead.
func (*IngestDocumentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *IngestDocumentRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *IngestDocumentRequest) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type IngestDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	KbId          string                 `protobuf:"bytes,2,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 失败原因/跳过原因（非文本类等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestDocumentResponse) Reset() {
	*x = IngestDocumentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestDocumentResponse) ProtoMessage() {}

func (x *IngestDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestDocumentResponse.ProtoReflect.Descriptor instead.
func (*IngestDocumentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *IngestDocumentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IngestDocumentResponse) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *IngestDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                                                                    // Go 生成的 UUID，run 的规范身份（事件归属）
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // 会话/归属 + LangGraph thread 作用域
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`                                                                                 // 用户输入
	AgentType     string                 `protobuf:"bytes,4,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`                                                        // 本阶段 "react"
	MaxSteps      int32                  `protobuf:"varint,5,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`                                                          // ReAct 循环上限
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // trace_id / locale / owner_id 等（扁平）
	SchemaVersion string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`                                            // "v1"
	// —— M8 加性扩展（仍 v1，线兼容：旧端忽略高编号字段即降级）——
	// 已上传附件的引用（字节不过 gRPC：认知面持 MinIO 凭据按 key 直读，
	// 可任意时刻重读；Go 侧已校验 key 归属 uploads/{owner}/ 前缀）。
	Attachments   []*Attachment `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RunRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RunRequest) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *RunRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RunRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RunRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// 上传附件引用（对象存储 key + 展示元信息）。与 ArtifactRef 的区别：
// ArtifactRef 是"运行产物"（含预览/下载 URL，事件流出）；Attachment 是"用户输入"
// （仅入参引用，不进事件流——用户气泡由前端自渲染）。
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceKey   string                 `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"` // uploads/{owner}/{session}/{uuid8}-{fileName}
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 每 run 单调、无空洞、从 1；由 Python（因果源）分配
	RunId     string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	MessageId string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 原位更新键；TOOL_CALL 时 == tool_call_id
	Type      EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=agent.v1.EventType" json:"type,omitempty"`
	TsUnixMs  int64                  `protobuf:"varint,5,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"` // Python 发射时间 → SSE messageTime
	IsFinal   bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`      // 本条消息终态
	Finish    bool                   `protobuf:"varint,7,opt,name=finish,proto3" json:"finish,omitempty"`                       // 整个 run 终态；仅 RESULT 为 true
	Step      string                 `protobuf:"bytes,8,opt,name=step,proto3" json:"step,omitempty"`                            // ReAct 步序/节点名（可观测）
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_ToolThought
	//	*Event_ToolCall
	//	*Event_ToolResult
	//	*Event_Result
	//	*Event_Plan
	//	*Event_Task
	//	*Event_Approval
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *Event) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Event) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

func (x *Event) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetToolThought() *ThoughtPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolThought); ok {
			return x.ToolThought
		}
	}
	return nil
}

func (x *Event) GetToolCall() *ToolPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Event) GetToolResult() *ToolPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *Event) GetResult() *ResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Event) GetPlan() *PlanPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Plan); ok {
			return x.Plan
		}
	}
	return nil
}

func (x *Event) GetTask() *TaskPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Event) GetApproval() *ApprovalPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_ToolThought struct {
	ToolThought *ThoughtPayload `protobuf:"bytes,16,opt,name=tool_thought,json=toolThought,proto3,oneof"` // 也用于 PLAN_THOUGHT（按 type 区分）
}

type Event_ToolCall struct {
	ToolCall *ToolPayload `protobuf:"bytes,17,opt,name=tool_call,json=toolCall,proto3,oneof"` // RUNNING / SUCCESS / FAILED
}

type Event_ToolResult struct {
	ToolResult *ToolPayload `protobuf:"bytes,18,opt,name=tool_result,json=toolResult,proto3,oneof"` // 复用同结构，携带 observation + artifacts
}

type Event_Result struct {
	Result *ResultPayload `protobuf:"bytes,19,opt,name=result,proto3,oneof"`
}

type Event_Plan struct {
	Plan *PlanPayload `protobuf:"bytes,20,opt,name=plan,proto3,oneof"`
}

type Event_Task struct {
	Task *TaskPayload `protobuf:"bytes,21,opt,name=task,proto3,oneof"`
}

type Event_Approval struct {
	Approval *ApprovalPayload `protobuf:"bytes,22,opt,name=approval,proto3,oneof"` // M11 HITL
}

func (*Event_ToolThought) isEvent_Payload() {}

func (*Event_ToolCall) isEvent_Payload() {}

func (*Event_ToolResult) isEvent_Payload() {}

func (*Event_Result) isEvent_Payload() {}

func (*Event_Plan) isEvent_Payload() {}

func (*Event_Task) isEvent_Payload() {}

func (*Event_Approval) isEvent_Payload() {}

type ThoughtPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PlannerRoundId string                 `protobuf:"bytes,2,opt,name=planner_round_id,json=plannerRoundId,proto3" json:"planner_round_id,omitempty"` // 仅 plan_thought 填写；executor 的 tool_thought 留空
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThoughtPayload) Reset() {
	*x = ThoughtPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtPayload) ProtoMessage() {}

func (x *ThoughtPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtPayload.ProtoReflect.Descriptor instead.
func (*ThoughtPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ThoughtPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ThoughtPayload) GetPlannerRoundId() string {
	if x != nil {
		return x.PlannerRoundId
	}
	return ""
}

// 计划快照（plan 事件）：steps/step_status/notes 并行索引。
type PlanPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Steps          []string               `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	StepStatus     []string               `protobuf:"bytes,3,rep,name=step_status,json=stepStatus,proto3" json:"step_status,omitempty"` // not_started | in_progress | completed | blocked
	Notes          []string               `protobuf:"bytes,4,rep,name=notes,proto3" json:"notes,omitempty"`
	PlannerRoundId string                 `protobuf:"bytes,5,opt,name=planner_round_id,json=plannerRoundId,proto3" json:"planner_round_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanPayload) Reset() {
	*x = PlanPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPayload) ProtoMessage() {}

func (x *PlanPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPayload.ProtoReflect.Descriptor instead.
func (*PlanPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PlanPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlanPayload) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *PlanPayload) GetStepStatus() []string {
	if x != nil {
		return x.StepStatus
	}
	return nil
}

func (x *PlanPayload) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *PlanPayload) GetPlannerRoundId() string {
	if x != nil {
		return x.PlannerRoundId
	}
	return ""
}

// 单个子任务（task 事件，由 currentStep 按 "<sep>" 切分而来）。
type TaskPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskPayload) Reset() {
	*x = TaskPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskPayload) ProtoMessage() {}

func (x *TaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskPayload.ProtoReflect.Descriptor instead.
func (*TaskPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ToolPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // == Event.message_id（TOOL_CALL）
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolProvider  string                 `protobuf:"bytes,3,opt,name=tool_provider,json=toolProvider,proto3" json:"tool_provider,omitempty"`     // 本阶段 "local"
	Status        ToolCallStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=agent.v1.ToolCallStatus" json:"status,omitempty"`       // running → success | failed
	DispatchIndex int32                  `protobuf:"varint,5,opt,name=dispatch_index,json=dispatchIndex,proto3" json:"dispatch_index,omitempty"` // 同一轮内工具顺序
	Input         *structpb.Struct       `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`                                       // 解析后的参数对象（非字符串）
	ToolResult    string                 `protobuf:"bytes,7,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`           // observation 文本（TOOL_RESULT 用）
	Summary       string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`                                   // "正在调用 X" / "X 调用完成" / "X 调用失败"
	ErrorMsg      string                 `protobuf:"bytes,9,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`                 // FAILED 时
	ArtifactRefs  []*ArtifactRef         `protobuf:"bytes,10,rep,name=artifact_refs,json=artifactRefs,proto3" json:"artifact_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolPayload) Reset() {
	*x = ToolPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolPayload) ProtoMessage() {}

func (x *ToolPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolPayload.ProtoReflect.Descriptor instead.
func (*ToolPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ToolPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolPayload) GetToolProvider() string {
	if x != nil {
		return x.ToolProvider
	}
	return ""
}

func (x *ToolPayload) GetStatus() ToolCallStatus {
	if x != nil {
		return x.Status
	}
	return ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED
}

func (x *ToolPayload) GetDispatchIndex() int32 {
	if x != nil {
		return x.DispatchIndex
	}
	return 0
}

func (x *ToolPayload) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolPayload) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *ToolPayload) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ToolPayload) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ToolPayload) GetArtifactRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactRefs
	}
	return nil
}

// M11 · 人工审批请求：受保护工具在执行前经 LangGraph interrupt 挂起，
// run 以"审批=run 边界"收尾（本事件 finish=false + 随后的挂起 RESULT finish=true）；
// 决议经 POST /runs/{id}/approvals 以 resume metadata 开新 run 继续（PG checkpoint 续图）。
type ApprovalPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId         string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`                             // 挂起时生成，checkpoint 持久（重放重生成值不外泄）
	ToolName           string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`                                   // 受保护工具名
	Input              *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`                                                         // 工具入参预览（用户据此决策）
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                                       // 为什么需要审批（配置说明）
	PendingToolCallIds []string               `protobuf:"bytes,5,rep,name=pending_tool_call_ids,json=pendingToolCallIds,proto3" json:"pending_tool_call_ids,omitempty"` // run1 中已发 RUNNING 的工具卡（前端翻"待审批"防孤儿转圈）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApprovalPayload) Reset() {
	*x = ApprovalPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalPayload) ProtoMessage() {}

func (x *ApprovalPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalPayload.ProtoReflect.Descriptor instead.
func (*ApprovalPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalPayload) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ApprovalPayload) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ApprovalPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApprovalPayload) GetPendingToolCallIds() []string {
	if x != nil {
		return x.PendingToolCallIds
	}
	return nil
}

// M11 · 累计 token 用量（mapper 全 run 聚合，随终态 RESULT 附带；Go 落 runs 表）。
type UsageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ModelCalls    int32                  `protobuf:"varint,3,opt,name=model_calls,json=modelCalls,proto3" json:"model_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageInfo) Reset() {
	*x = UsageInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageInfo) ProtoMessage() {}

func (x *UsageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageInfo.ProtoReflect.Descriptor instead.
func (*UsageInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UsageInfo) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageInfo) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageInfo) GetModelCalls() int32 {
	if x != nil {
		return x.ModelCalls
	}
	return 0
}

type ResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 最终答复
	ArtifactRefs  []*ArtifactRef         `protobuf:"bytes,2,rep,name=artifact_refs,json=artifactRefs,proto3" json:"artifact_refs,omitempty"`
	Usage         *UsageInfo             `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"` // M11 加性；缺省=旧端零值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultPayload) Reset() {
	*x = ResultPayload{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultPayload) ProtoMessage() {}

func (x *ResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultPayload.ProtoReflect.Descriptor instead.
func (*ResultPayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ResultPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ResultPayload) GetArtifactRefs() []*ArtifactRef {
	if x != nil {
		return x.ArtifactRefs
	}
	return nil
}

func (x *ResultPayload) GetUsage() *UsageInfo {
	if x != nil {
		return x.Usage
	}
	return nil
}

// 沿用原项目 8 字段形状：artifact UI 零改、缺文件降级显式。
type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceKey   string                 `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PreviewUrl    string                 `protobuf:"bytes,3,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Missing       bool                   `protobuf:"varint,8,opt,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactRef) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *ArtifactRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactRef) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *ArtifactRef) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ArtifactRef) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ArtifactRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ArtifactRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactRef) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1cgoogle/protobuf/struct.proto\"h\n" +
	"\x15IngestDocumentRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x124\n" +
	"\n" +
	"attachment\x18\x02 \x01(\v2\x14.agent.v1.AttachmentR\n" +
	"attachment\"W\n" +
	"\x16IngestDocumentResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x13\n" +
	"\x05kb_id\x18\x02 \x01(\tR\x04kbId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf0\x02\n" +
	"\n" +
	"RunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x04 \x01(\tR\tagentType\x12\x1b\n" +
	"\tmax_steps\x18\x05 \x01(\x05R\bmaxSteps\x12>\n" +
	"\bmetadata\x18\x06 \x03(\v2\".agent.v1.RunRequest.MetadataEntryR\bmetadata\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x126\n" +
	"\vattachments\x18\b \x03(\v2\x14.agent.v1.AttachmentR\vattachments\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\n" +
	"Attachment\x12!\n" +
	"\fresource_key\x18\x01 \x01(\tR\vresourceKey\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\xdd\x04\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.agent.v1.EventTypeR\x04type\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x05 \x01(\x03R\btsUnixMs\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x12\x16\n" +
	"\x06finish\x18\a \x01(\bR\x06finish\x12\x12\n" +
	"\x04step\x18\b \x01(\tR\x04step\x12=\n" +
	"\ftool_thought\x18\x10 \x01(\v2\x18.agent.v1.ThoughtPayloadH\x00R\vtoolThought\x124\n" +
	"\ttool_call\x18\x11 \x01(\v2\x15.agent.v1.ToolPayloadH\x00R\btoolCall\x128\n" +
	"\vtool_result\x18\x12 \x01(\v2\x15.agent.v1.ToolPayloadH\x00R\n" +
	"toolResult\x121\n" +
	"\x06result\x18\x13 \x01(\v2\x17.agent.v1.ResultPayloadH\x00R\x06result\x12+\n" +
	"\x04plan\x18\x14 \x01(\v2\x15.agent.v1.PlanPayloadH\x00R\x04plan\x12+\n" +
	"\x04task\x18\x15 \x01(\v2\x15.agent.v1.TaskPayloadH\x00R\x04task\x127\n" +
	"\bapproval\x18\x16 \x01(\v2\x19.agent.v1.ApprovalPayloadH\x00R\bapprovalB\t\n" +
	"\apayload\"N\n" +
	"\x0eThoughtPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12(\n" +
	"\x10planner_round_id\x18\x02 \x01(\tR\x0eplannerRoundId\"\x9a\x01\n" +
	"\vPlanPayload\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05steps\x18\x02 \x03(\tR\x05steps\x12\x1f\n" +
	"\vstep_status\x18\x03 \x03(\tR\n" +
	"stepStatus\x12\x14\n" +
	"\x05notes\x18\x04 \x03(\tR\x05notes\x12(\n" +
	"\x10planner_round_id\x18\x05 \x01(\tR\x0eplannerRoundId\"!\n" +
	"\vTaskPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x8d\x03\n" +
	"\vToolPayload\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12#\n" +
	"\rtool_provider\x18\x03 \x01(\tR\ftoolProvider\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.agent.v1.ToolCallStatusR\x06status\x12%\n" +
	"\x0edispatch_index\x18\x05 \x01(\x05R\rdispatchIndex\x12-\n" +
	"\x05input\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05input\x12\x1f\n" +
	"\vtool_result\x18\a \x01(\tR\n" +
	"toolResult\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12\x1b\n" +
	"\terror_msg\x18\t \x01(\tR\berrorMsg\x12:\n" +
	"\rartifact_refs\x18\n" +
	" \x03(\v2\x15.agent.v1.ArtifactRefR\fartifactRefs\"\xc9\x01\n" +
	"\x0fApprovalPayload\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x121\n" +
	"\x15pending_tool_call_ids\x18\x05 \x03(\tR\x12pendingToolCallIds\"t\n" +
	"\tUsageInfo\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12\x1f\n" +
	"\vmodel_calls\x18\x03 \x01(\x05R\n" +
	"modelCalls\"\x8a\x01\n" +
	"\rResultPayload\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12:\n" +
	"\rartifact_refs\x18\x02 \x03(\v2\x15.agent.v1.ArtifactRefR\fartifactRefs\x12)\n" +
	"\x05usage\x18\x03 \x01(\v2\x13.agent.v1.UsageInfoR\x05usage\"\xf0\x01\n" +
	"\vArtifactRef\x12!\n" +
	"\fresource_key\x18\x01 \x01(\tR\vresourceKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vpreview_url\x18\x03 \x01(\tR\n" +
	"previewUrl\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x18\n" +
	"\amissing\x18\b \x01(\bR\amissing*\xf9\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_TOOL_THOUGHT\x10\x01\x12\x18\n" +
	"\x14EVENT_TYPE_TOOL_CALL\x10\x02\x12\x1a\n" +
	"\x16EVENT_TYPE_TOOL_RESULT\x10\x03\x12\x15\n" +
	"\x11EVENT_TYPE_RESULT\x10\x04\x12\x1b\n" +
	"\x17EVENT_TYPE_PLAN_THOUGHT\x10\x05\x12\x13\n" +
	"\x0fEVENT_TYPE_PLAN\x10\x06\x12\x13\n" +
	"\x0fEVENT_TYPE_TASK\x10\a\x12\x1f\n" +
	"\x1bEVENT_TYPE_APPROVAL_REQUEST\x10\b*\x8b\x01\n" +
	"\x0eToolCallStatus\x12 \n" +
	"\x1cTOOL_CALL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_SUCCESS\x10\x02\x12\x1b\n" +
	"\x17TOOL_CALL_STATUS_FAILED\x10\x032\x97\x01\n" +
	"\x10CognitionService\x12.\n" +
	"\x03Run\x12\x14.agent.v1.RunRequest\x1a\x0f.agent.v1.Event0\x01\x12S\n" +
	"\x0eIngestDocument\x12\x1f.agent.v1.IngestDocumentRequest\x1a .agent.v1.IngestDocumentResponseB;Z9my-agent/control-plane/internal/genproto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_v1_agent_proto_goTypes = []any{
	(EventType)(0),                 // 0: agent.v1.EventType
	(ToolCallStatus)(0),            // 1: agent.v1.ToolCallStatus
	(*IngestDocumentRequest)(nil),  // 2: agent.v1.IngestDocumentRequest
	(*IngestDocumentResponse)(nil), // 3: agent.v1.IngestDocumentResponse
	(*RunRequest)(nil),             // 4: agent.v1.RunRequest
	(*Attachment)(nil),             // 5: agent.v1.Attachment
	(*Event)(nil),                  // 6: agent.v1.Event
	(*ThoughtPayload)(nil),         // 7: agent.v1.ThoughtPayload
	(*PlanPayload)(nil),            // 8: agent.v1.PlanPayload
	(*TaskPayload)(nil),            // 9: agent.v1.TaskPayload
	(*ToolPayload)(nil),            // 10: agent.v1.ToolPayload
	(*ApprovalPayload)(nil),        // 11: agent.v1.ApprovalPayload
	(*UsageInfo)(nil),              // 12: agent.v1.UsageInfo
	(*ResultPayload)(nil),          // 13: agent.v1.ResultPayload
	(*ArtifactRef)(nil),            // 14: agent.v1.ArtifactRef
	nil,                            // 15: agent.v1.RunRequest.MetadataEntry
	(*structpb.Struct)(nil),        // 16: google.protobuf.Struct
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.IngestDocumentRequest.attachment:type_name -> agent.v1.Attachment
	15, // 1: agent.v1.RunRequest.metadata:type_name -> agent.v1.RunRequest.MetadataEntry
	5,  // 2: agent.v1.RunRequest.attachments:type_name -> agent.v1.Attachment
	0,  // 3: agent.v1.Event.type:type_name -> agent.v1.EventType
	7,  // 4: agent.v1.Event.tool_thought:type_name -> agent.v1.ThoughtPayload
	10, // 5: agent.v1.Event.tool_call:type_name -> agent.v1.ToolPayload
	10, // 6: agent.v1.Event.tool_result:type_name -> agent.v1.ToolPayload
	13, // 7: agent.v1.Event.result:type_name -> agent.v1.ResultPayload
	8,  // 8: agent.v1.Event.plan:type_name -> agent.v1.PlanPayload
	9,  // 9: agent.v1.Event.task:type_name -> agent.v1.TaskPayload
	11, // 10: agent.v1.Event.approval:type_name -> agent.v1.ApprovalPayload
	1,  // 11: agent.v1.ToolPayload.status:type_name -> agent.v1.ToolCallStatus
	16, // 12: agent.v1.ToolPayload.input:type_name -> google.protobuf.Struct
	14, // 13: agent.v1.ToolPayload.artifact_refs:type_name -> agent.v1.ArtifactRef
	16, // 14: agent.v1.ApprovalPayload.input:type_name -> google.protobuf.Struct
	14, // 15: agent.v1.ResultPayload.artifact_refs:type_name -> agent.v1.ArtifactRef
	12, // 16: agent.v1.ResultPayload.usage:type_name -> agent.v1.UsageInfo
	4,  // 17: agent.v1.CognitionService.Run:input_type -> agent.v1.RunRequest
	2,  // 18: agent.v1.CognitionService.IngestDocument:input_type -> agent.v1.IngestDocumentRequest
	6,  // 19: agent.v1.CognitionService.Run:output_type -> agent.v1.Event
	3,  // 20: agent.v1.CognitionService.IngestDocument:output_type -> agent.v1.IngestDocumentResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*Event_ToolThought)(nil),
		(*Event_ToolCall)(nil),
		(*Event_ToolResult)(nil),
		(*Event_Result)(nil),
		(*Event_Plan)(nil),
		(*Event_Task)(nil),
		(*Event_Approval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
