// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CognitionService_Run_FullMethodName            = "/agent.v1.CognitionService/Run"
	CognitionService_IngestDocument_FullMethodName = "/agent.v1.CognitionService/IngestDocument"
)

// CognitionServiceClient is the client API for CognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 认知服务：一次 run = 一个 server-streaming RPC，流的顺序即事件顺序。
// 客户端（Go 控制面）取消 ctx → 该 RPC 被取消（CANCELLED）→ Python 取消图执行。
type CognitionServiceClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// —— UX-1 加性扩展（仍 v1）：Files 面板"上传即入库"（不经对话轮）。
	// 入库必须走认知面：embedding/分块是认知域能力，Go 不持向量化逻辑。
	// 读/删走 Go 直连 Qdrant REST（纯管理读写，无向量化，见 control-plane/internal/kb）。
	IngestDocument(ctx context.Context, in *IngestDocumentRequest, opts ...grpc.CallOption) (*IngestDocumentResponse, error)
}

type cognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCognitionServiceClient(cc grpc.ClientConnInterface) CognitionServiceClient {
	return &cognitionServiceClient{cc}
}

func (c *cognitionServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitionService_ServiceDesc.Streams[0], CognitionService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitionService_RunClient = grpc.ServerStreamingClient[Event]

func (c *cognitionServiceClient) IngestDocument(ctx context.Context, in *IngestDocumentRequest, opts ...grpc.CallOption) (*IngestDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestDocumentResponse)
	err := c.cc.Invoke(ctx, CognitionService_IngestDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognitionServiceServer is the server API for CognitionService service.
// All implementations must embed UnimplementedCognitionServiceServer
// for forward compatibility.
//
// 认知服务：一次 run = 一个 server-streaming RPC，流的顺序即事件顺序。
// 客户端（Go 控制面）取消 ctx → 该 RPC 被取消（CANCELLED）→ Python 取消图执行。
type CognitionServiceServer interface {
	Run(*RunRequest, grpc.ServerStreamingServer[Event]) error
	// —— UX-1 加性扩展（仍 v1）：Files 面板"上传即入库"（不经对话轮）。
	// 入库必须走认知面：embedding/分块是认知域能力，Go 不持向量化逻辑。
	// 读/删走 Go 直连 Qdrant REST（纯管理读写，无向量化，见 control-plane/internal/kb）。
	IngestDocument(context.Context, *IngestDocumentRequest) (*IngestDocumentResponse, error)
	mustEmbedUnimplementedCognitionServiceServer()
}

// UnimplementedCognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognitionServiceServer struct{}

func (UnimplementedCognitionServiceServer) Run(*RunRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCognitionServiceServer) IngestDocument(context.Context, *IngestDocumentRequest) (*IngestDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestDocument not implemented")
}
func (UnimplementedCognitionServiceServer) mustEmbedUnimplementedCognitionServiceServer() {}
func (UnimplementedCognitionServiceServer) testEmbeddedByValue()                          {}

// UnsafeCognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognitionServiceServer will
// result in compilation errors.
type UnsafeCognitionServiceServer interface {
	mustEmbedUnimplementedCognitionServiceServer()
}

func RegisterCognitionServiceServer(s grpc.ServiceRegistrar, srv CognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedCognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognitionService_ServiceDesc, srv)
}

func _CognitionService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitionServiceServer).Run(m, &grpc.GenericServerStream[RunRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitionService_RunServer = grpc.ServerStreamingServer[Event]

func _CognitionService_IngestDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitionServiceServer).IngestDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitionService_IngestDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitionServiceServer).IngestDocument(ctx, req.(*IngestDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CognitionService_ServiceDesc is the grpc.ServiceDesc for CognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.CognitionService",
	HandlerType: (*CognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestDocument",
			Handler:    _CognitionService_IngestDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _CognitionService_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
