// Package agentv1 holds the generated Go bindings for the agent-go cognition
// gRPC service (agent/v1/agent.proto).
//
// The .proto source of truth lives in the agent-go repository, not here. To
// regenerate after the contract changes, run protoc-gen-go and
// protoc-gen-go-grpc against agent-go's agent/v1/agent.proto and output into
// internal/genproto using the module path github.com/LingMi1/code-review-agent.
// The committed files were generated by protoc-gen-go v1.36.11.
package agentv1
